### PR TITLE
Update to JOSM 16043

### PR DESCRIPTION
**Pull request by don-vip**
See https://josm.openstreetmap.de/changeset/16043/josm/

### CODE REVIEW

**Comment by don-vip** [comment]
@maripo can you please merge this pull request? Otherwise I will need to remove the plugin from the JOSM default list.

**Comment by don-vip** [comment]
I've removed the plugin from the default list: https://josm.openstreetmap.de/wiki/PluginsSource?action=diff&version=522

**Comment by maripo** [comment]
Thank you for late reply.
I confirmed that it was successfully built and worked well with 16043.
https://github.com/maripo/JOSM_easypresets/releases/tag/v1.15
Is it OK to add it again to the plugin list?

**Comment by don-vip** [comment]
@maripo thank you! I have added v1.15 back in the plugin list

**Pull request merged**
